namespace Math.Presentation

module MathematicalStandardizedVariants = 

    let zero =                     "\u0030\ufe00"
    let emptySet =                 "\u2205\ufe00"
    let intersection =             "\u2229\ufe00" 
    let union =                    "\u222a\ufe00"
    let lessThanButNotEqualTo =    "\u2268\ufe00"
    let greaterThanButNotEqualTo = "\u2269\ufe00"
    let lessThanOrEquivalentTo =   "\u2272\ufe00"
    let greaterThanOrEquivalentTo ="\u2273\ufe00"
    let subSetOfWithNotEqualTo =   "\u228a\ufe00"
    let superSetOfWithNotEqualTo = "\u228b\ufe00"
    let squareCap =                "\u2293\ufe00"
    let squareCup =                "\u2294\ufe00"
    let circledPlus =              "\u2295\ufe00"
    let circledTimes=              "\u2297\ufe00"
    let circledEquals =            "\u229c\ufe00"
    let lessThanEqualToOrGreaterThan = "\u22da\ufe00"
    let greaterThanEqualToOrLessThan = "\u22db\ufe00"
    let interiorProduct =          "\u2a3c\ufe00"
    let righthandInteriorProduct = "\u2a3d\ufe00"
    let similarOrLessThan =        "\u2a9d\ufe00"
    let similarOrGreaterThan =     "\u2a9e\ufe00"
    let smallerThanOrEqualTo =     "\u2aac\ufe00"
    let largerThanOrEqualTo =      "\u2aad\ufe00"
    let subSetOfAboveNotEqualTo =  "\u2acb\ufe00"
    let superSetOfAboveNotEqualTo ="\u2acc\ufe00"
    